/* Generated by chroma.py v1.0.0 — semantic theme tokens. */
/* Flat Layer 2 semantic palette. Component tokens (Layer 3) belong in
   the code layer. */
export const chromaTheme = {
  light: {
    bgSurfaceRoot: '#fbfcfe',
    bgSurfaceDefault: '#f7f8fc',
    bgSurfaceSubtle: '#f4f5f9',
    bgSurfaceHover: '#f1f2f7',
    bgSurfaceActive: '#eff0f5',
    bgSurfaceOverlay: '#ffffff',
    borderSubtle: '#e9eaf0',
    borderDefault: '#dddee4',
    borderStrong: '#cacbd1',
    textDisabled: '#cacbd1',
    textMuted: '#717279',
    textSecondary: '#2d2e34',
    textPrimary: '#05050a',
    textOnAccent: '#000000',
    bgActionPrimary: '#d7e8ff',
    bgActionHover: '#d5e6ff',
    bgActionActive: '#daebff',
  },
  dark: {
    bgSurfaceRoot: '#0c0d12',
    bgSurfaceDefault: '#111218',
    bgSurfaceSubtle: '#17181e',
    bgSurfaceHover: '#1c1e25',
    bgSurfaceActive: '#22242c',
    bgSurfaceOverlay: '#3b3d45',
    borderSubtle: '#31333d',
    borderDefault: '#3f414c',
    borderStrong: '#545663',
    textDisabled: '#545663',
    textMuted: '#a0a3b3',
    textSecondary: '#cccfe1',
    textPrimary: '#eff2ff',
    textOnAccent: '#000000',
    bgActionPrimary: '#d7e8ff',
    bgActionHover: '#d5e6ff',
    bgActionActive: '#daebff',
  },
} as const;

export type ChromaTheme = typeof chromaTheme;
