/* Generated by chroma.py v1.2.0 — semantic theme config. */
/* Color utilities resolve to runtime CSS custom properties defined in the
   companion .css file (:root for light, .dark for dark). Only the four core
   semantic domains are exposed; the tiers are chained via var() (semantic ->
   global). */
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // surfaces - canvas, cards, hover/active rows, status tints
        surface: { root: 'var(--bg-surface-root)', default: 'var(--bg-surface-default)', subtle: 'var(--bg-surface-subtle)', hover: 'var(--bg-surface-hover)', active: 'var(--bg-surface-active)', overlay: 'var(--bg-surface-overlay)', success-subtle: 'var(--bg-success-subtle)', success-strong: 'var(--bg-success-strong)', warning-subtle: 'var(--bg-warning-subtle)', warning-strong: 'var(--bg-warning-strong)', danger-subtle: 'var(--bg-danger-subtle)', danger-strong: 'var(--bg-danger-strong)', info-subtle: 'var(--bg-info-subtle)', info-strong: 'var(--bg-info-strong)' },
        // text - primary, secondary, muted, disabled, status
        foreground: { primary: 'var(--text-primary)', secondary: 'var(--text-secondary)', muted: 'var(--text-muted)', disabled: 'var(--text-disabled)', success: 'var(--text-success)', warning: 'var(--text-warning)', danger: 'var(--text-danger)', info: 'var(--text-info)' },
        // borders - subtle rules, boundaries, focus, status
        border: { subtle: 'var(--border-subtle)', default: 'var(--border-default)', strong: 'var(--border-strong)', success: 'var(--border-success)', warning: 'var(--border-warning)', danger: 'var(--border-danger)', info: 'var(--border-info)' },
        // on-color - labels on accent and status surfaces
        on: { accent: 'var(--text-on-accent)', success: 'var(--text-on-success)', warning: 'var(--text-on-warning)', danger: 'var(--text-on-danger)', info: 'var(--text-on-info)' },
        // actions - brand execution buttons
        action: { primary: 'var(--bg-action-primary)', hover: 'var(--bg-action-hover)', active: 'var(--bg-action-active)' },
      },
    },
  },
};
