/* Generated by chroma.py v1.0.0 — semantic theme config. */
/* Color utilities resolve to runtime CSS custom properties defined in the
   companion .css file (:root for light, .dark for dark). Only the four core
   semantic domains are exposed; the tiers are chained via var() (semantic ->
   global). */
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // surfaces - canvas, cards, hover/active rows
        surface: { root: 'var(--bg-surface-root)', default: 'var(--bg-surface-default)', subtle: 'var(--bg-surface-subtle)', hover: 'var(--bg-surface-hover)', active: 'var(--bg-surface-active)', overlay: 'var(--bg-surface-overlay)' },
        // text - primary, secondary, muted, disabled
        foreground: { primary: 'var(--text-primary)', secondary: 'var(--text-secondary)', muted: 'var(--text-muted)', disabled: 'var(--text-disabled)' },
        // borders - subtle rules, boundaries, focus
        border: { subtle: 'var(--border-subtle)', default: 'var(--border-default)', strong: 'var(--border-strong)' },
        // on-color - label on accent surfaces
        on: { accent: 'var(--text-on-accent)' },
        // actions - brand execution buttons
        action: { primary: 'var(--bg-action-primary)', hover: 'var(--bg-action-hover)', active: 'var(--bg-action-active)' },
      },
    },
  },
};
