"""chroma.py — deterministic semantic theme generation for enterprise frontends.

Weave a complete, dual-theme (Light/Dark) semantic token configuration from a
single structural brand hue coordinate, compiled in OKLCH across two Atmos
tiers: global (raw math) and semantic (functional intent).
"""

__version__ = "1.2.0"

from chroma.color import (
    contrast_ratio,
    hsl_to_rgb,
    oklch_to_hex,
    oklch_to_rgb,
    parse_hex,
    relative_luminance,
    rgb_to_hex,
    rgb_to_hsl,
    rgb_to_oklch,
)
from chroma.serializers import (
    emit_css,
    emit_dtcg,
    emit_figma,
    emit_json,
    emit_less,
    emit_sass,
    emit_stylus,
    emit_ts,
    serialize_css,
    serialize_dtcg,
    serialize_figma,
    serialize_figma_mode,
    serialize_json,
    serialize_less,
    serialize_sass,
    serialize_stylus,
    serialize_tailwind_v3_config,
    serialize_tailwind_v3_css,
    serialize_tailwind_v4_css,
    serialize_ts,
)
from chroma.tokens import (
    ACCENT_TOKEN_NAMES,
    BRAND_SCALE_NAMES,
    DARK,
    LIGHT,
    SCALE_STEP_LEGEND,
    SEMANTIC_TO_GLOBAL,
    STATUS_COORD_NAMES,
    STATUS_FAMILIES,
    STATUS_SCALE_NAMES,
    STATUS_SPECS,
    STATUS_TOKEN_NAMES,
    STEP_KEYS,
    THEMES,
    accent_scale,
    brand_scale_steps,
    build_layers,
    color_ramp,
    neutral_steps,
    status_scale,
    status_scale_steps,
    verify_contrast,
)

__all__ = [
    "ACCENT_TOKEN_NAMES",
    "BRAND_SCALE_NAMES",
    "DARK",
    "LIGHT",
    "SCALE_STEP_LEGEND",
    "SEMANTIC_TO_GLOBAL",
    "STATUS_COORD_NAMES",
    "STATUS_FAMILIES",
    "STATUS_SCALE_NAMES",
    "STATUS_SPECS",
    "STATUS_TOKEN_NAMES",
    "STEP_KEYS",
    "THEMES",
    "accent_scale",
    "brand_scale_steps",
    "build_layers",
    "color_ramp",
    "contrast_ratio",
    "emit_css",
    "emit_dtcg",
    "emit_figma",
    "emit_json",
    "emit_less",
    "emit_sass",
    "emit_stylus",
    "emit_ts",
    "hsl_to_rgb",
    "neutral_steps",
    "oklch_to_hex",
    "oklch_to_rgb",
    "parse_hex",
    "relative_luminance",
    "rgb_to_hex",
    "rgb_to_hsl",
    "rgb_to_oklch",
    "status_scale",
    "status_scale_steps",
    "serialize_css",
    "serialize_dtcg",
    "serialize_figma",
    "serialize_figma_mode",
    "serialize_json",
    "serialize_less",
    "serialize_sass",
    "serialize_stylus",
    "serialize_tailwind_v3_config",
    "serialize_tailwind_v3_css",
    "serialize_tailwind_v4_css",
    "serialize_ts",
    "verify_contrast",
]
