"""Serializers: JSON and Tailwind (v3 config + companion CSS, v4 stylesheet)."""

from __future__ import annotations

import json
import sys
from pathlib import Path

from chroma import __version__
from chroma.color import parse_hex, rgb_to_hsl, rgb_to_oklch
from chroma.tokens import NEUTRAL_TOKEN_STEPS, THEMES

INTENT_TOKEN_NAMES = (
    "intent-primary",
    "intent-primary-hover",
    "intent-primary-active",
    "intent-on-primary",
    "intent-focus-ring",
)


def _token_order() -> list[str]:
    return list(NEUTRAL_TOKEN_STEPS) + list(INTENT_TOKEN_NAMES)


def _format_oklch(value: tuple[float, float, float]) -> str:
    lightness, chroma, hue = value
    return f"{lightness:.4f} {chroma:.4f} {hue:.2f}"


def _oklch_map(themes: dict[str, dict[str, str]]) -> dict[str, dict[str, str]]:
    brand_order = list(NEUTRAL_TOKEN_STEPS) + list(INTENT_TOKEN_NAMES)
    oklch: dict[str, dict[str, str]] = {}
    for theme_name, tokens in themes.items():
        oklch[theme_name] = {
            name: _format_oklch(rgb_to_oklch(parse_hex(tokens[name])))
            for name in brand_order
        }
    return oklch


def _meta(brand_hex: str) -> dict:
    brand = parse_hex(brand_hex)
    lightness, chroma, hue = rgb_to_oklch(brand)
    hs, ss, ls = rgb_to_hsl(brand)
    return {
        "input": brand_hex,
        "engine": f"chroma.py {__version__}",
        "brand": {
            "oklch": [round(lightness, 4), round(chroma, 4), round(hue, 2)],
            "hsl": [round(hs, 2), round(ss, 4), round(ls, 4)],
        },
        "themes": list(THEMES),
    }


def serialize_json(themes: dict[str, dict[str, str]], brand_hex: str) -> str:
    """Serialize the token map as a JSON document with raw hex + OKLCH views."""
    payload = {
        "meta": _meta(brand_hex),
        **themes,
        "oklch": _oklch_map(themes),
    }
    return json.dumps(payload, indent=2) + "\n"


def _render_js_colors(themes: dict[str, dict[str, str]]) -> str:
    """Render the Tailwind ``theme.extend.colors`` object for v3 configs."""
    family_keys = {"surface": [], "text": [], "border": [], "intent": []}
    for name in _token_order():
        family = name.split("-", 1)[0]
        family_keys[family].append(name)
    lines = ["      colors: {"]
    for family, names in family_keys.items():
        members = ", ".join(
            f"{name.split('-', 1)[1]}: 'var(--{name})'" for name in names
        )
        lines.append(f"        {family}: {{ {members} }},")
    lines.append("      },")
    return "\n".join(lines)


def serialize_tailwind_v3_config(themes: dict[str, dict[str, str]]) -> str:
    """Serialize a Tailwind v3 ``tailwind.config.js`` (colors -> CSS vars)."""
    return f"""/* Generated by chroma.py v{__version__} — semantic theme config. */
/* Color utilities resolve to runtime CSS custom properties defined in the
   companion .css file (:root for light, .dark for dark). */
/** @type {{import('tailwindcss').Config}} */
module.exports = {{
  darkMode: 'class',
  theme: {{
    extend: {{
{_render_js_colors(themes)}
    }},
  }},
}};
"""


def serialize_tailwind_v3_css(themes: dict[str, dict[str, str]]) -> str:
    """Serialize the ``:root`` / ``.dark`` CSS variable definitions (v3 companion)."""
    lines = [
        f"/* Generated by chroma.py v{__version__} — semantic theme tokens. */",
        ":root {",
    ]
    for name in _token_order():
        lines.append(f"  --{name}: {themes['light'][name]};")
    lines.append("}")
    lines.append("")
    lines.append(".dark {")
    for name in _token_order():
        lines.append(f"  --{name}: {themes['dark'][name]};")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def serialize_tailwind_v4_css(themes: dict[str, dict[str, str]]) -> str:
    """Serialize a self-contained Tailwind v4 theme stylesheet (``@theme`` + vars)."""
    lines = [f"/* Generated by chroma.py v{__version__} — semantic theme tokens. */"]
    lines += [
        "@import 'tailwindcss';",
        "",
        "@custom-variant dark (&:where(.dark, .dark *));",
        "",
        "@theme inline {",
    ]
    for name in _token_order():
        lines.append(f"  --color-{name}: var(--{name});")
    lines += ["}", "", ":root {"]
    for name in _token_order():
        lines.append(f"  --{name}: {themes['light'][name]};")
    lines += ["}", "", ".dark {"]
    for name in _token_order():
        lines.append(f"  --{name}: {themes['dark'][name]};")
    lines += ["}", ""]
    return "\n".join(lines)


def emit_tailwind(themes: dict[str, dict[str, str]], output: str | None) -> None:
    """Resolve the tailwind format by output target.

    No ``-o`` (stdout) or a ``.css`` target emits a self-contained v4
    stylesheet. Any other target emits a v3 ``config.js`` plus its companion
    ``.css`` variable file.
    """
    if output is None:
        sys.stdout.write(serialize_tailwind_v4_css(themes))
        return
    path = Path(output)
    if path.suffix == ".css":
        path.write_text(serialize_tailwind_v4_css(themes))
        print(f"wrote {path}", file=sys.stderr)
        return
    config = path if path.suffix == ".js" else path.with_suffix(".js")
    companion = config.with_suffix(".css")
    config.write_text(serialize_tailwind_v3_config(themes))
    companion.write_text(serialize_tailwind_v3_css(themes))
    print(f"wrote {config}", file=sys.stderr)
    print(f"wrote {companion}", file=sys.stderr)
